export const actionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRDOUCT: "SELECETED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    SET_PRODUCT_CATEGORY_FILER: "SET_PRODUCT_CATEGORY_FILER",
    SORT_ITEMS: "SORT_ITEMS",
    FILTER_ITEMS: "FILTER_ITEMS",
    ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
    REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
    INCREMENT_CART_ITEM: "INCREMENT_CART_ITEM",
    DECREMENT_CART_ITEM: "DECREMENT_CART_ITEM",
    DISPLAY_MODAL: "DISPLAY_MODAL",
    HIDE_MODAL: "HIDE_MODAL",
};